import pytest

from ib_users.exceptions.custom_exception_constants import \
    INVALID_EMAIL
from ib_users.validators.base_validator import \
    CustomException
from ib_users.utils.tests_utils import TestsUtils
from ib_users.validators import EmailValidator

@pytest.mark.parametrize("email",
                         ["","a@bc",
                          "hello.boy#gmail.com", "3010@gmail.l"])
def test_invalid_email(email):

    with pytest.raises(
            CustomException) as email_invalid_exception:
        EmailValidator.validate(email)
    TestsUtils.assert_custom_exception(
        INVALID_EMAIL,
        email_invalid_exception)


@pytest.mark.parametrize("email",
                         ["j@gm.co", "superuser@ibhubs.co",
                          "user@temp.com", "developer@mi.com"])
def test_valid_email(email):
    EmailValidator.validate(email)

